Fixing kernel module compilation
Without getting the return value, pwrite() would give the following
error when trying to compile the kernel module:

error: ignoring return value of 'pwrite' declared with attribute
warn_unused_result [-Werror=unused-result]

Signed-off-by: Brian Atkinson <batkinson@lanl.gov>