Fixing compilation error
Was getting the following error when compiling the user space versions
of zfs_racct_{read/write}():

error: unused paramter 'spa/flags' [-Werror=unused-parameter]

To fix this, I simply just added (void) spa and (void) flags to the user
space verion of the calls. This is following the style introduced by
other commits.

Signed-off-by: Brian Atkinson <batkinson@lanl.gov>